### PR TITLE
add resin image

### PR DESCRIPTION
**Pull request by bai-yang**
add resin image

### CODE REVIEW

**Comment by wu-sheng** [comment]
I will merge this pr, after the feature has been merged in sky-walking/master.

**Comment by wu-sheng** [comment]
From the snapshot of your issue, https://github.com/wu-sheng/sky-walking/issues/184#issue-225317810, the image seems a little deform and blurry. 

Please check the image is quadrate ( n * n ) and have the suitable resolution.

**Comment by wu-sheng** [comment]
@sky-walking/core-contributors

**Comment by bai-yang** [comment]
@wu-sheng ok, I will modify this image.

**Comment by bai-yang** [comment]
@wu-sheng  It is a square image, 200 * 200.

**Pull request merged**
