### PR TITLE
Support Memcache & Add MEMCACHE.png

### PR DESCRIPTION
**Pull request by IluckySi**
Support Memcache & Add MEMCACHE.png For SkyWalking-UI

### CODE REVIEW

**Comment by wu-sheng** [comment]
You need to adjust the icon to gray.

**Comment by wu-sheng** [comment]
@ascrutae If you have time, you can help him about the icon.

**Comment by ascrutae** [comment]
OK

**Comment by wu-sheng** [comment]
@ascrutae If you do so, please send a separate pr for that. Thanks.

**Comment by ascrutae** [comment]
@IluckySi Ref: #68

**Comment by wu-sheng** [comment]
Closing this, since we have #72

**Pull request closed without merging**
